version: "3"
services:
  nlp_server:
    container_name: server
    build: src/
    depends_on:
      - postgres_db
    env_file:
      - ./enviroments/dev/postgres_variables.env
      - ./enviroments/dev/enviroment_variables.env
    ports:
      - "8000:8000"
    volumes:
     - ./src:/app

  postgres_db:
    container_name: database
    restart: always
    build: db/
    #image: mdillon/postgis:latest
    env_file:
      - ./enviroments/dev/postgres_variables.env
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
