version: "3"
services:
  postgres:
    container_name: postgres
    restart: always
    image: mdillon/postgis:latest
    env_file:
      - ./enviroments/dev/postgres_variables.env
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/imports:/imports
    ports:
      - "5432:5432"
